In [11]:
import tensorflow as tf
import tensorflow.contrib.autograph as ag
@ag.convert()

def max_op(x1,x2):
    b=tf.where(tf.less_equal(x1,x2),x2,x1)
    return b
x1=tf.constant([2,3])
x2=tf.constant([4,2])
x=max_op(x1,x2)
with tf.Session() as sess:
    print(sess.run(x))

[4 3]


tf.maximum 函数

maximum(
    x,
    y,
    name=None
)
返回 x 和 y 的最大值（即表达式：x > y ? x : y）。

参数：
    x：张量。必须是下列类型之一：half，float32，float64，int32，int64。
    y：张量。必须与 x 具有相同的类型。
    name：操作的名称（可选）。

返回值：
该函数将返回一个张量并且与 x 具有相同的类型。

tf.minimum 函数

minimum(
    x,
    y,
    name=None
)
返回 x 和 y 的最小值（即表达式：x < y ? x : y）

参数：
    x：张量。必须是下列类型之一：half，float32，float64，int32，int64。
    y：张量。必须与 x 具有相同的类型。
    name：操作的名称（可选）。
返回值：
该函数将返回一个张量并且与 x 具有相同的类型。 

In [13]:
import tensorflow as tf
x1=tf.constant([1,23,3])
x2=tf.constant([2,3,4])
max_1=tf.maximum(x1,x2)
min_1=tf.minimum(x1,x2)
with tf.Session() as sess:
    print(sess.run(max_1))
    print(sess.run(min_1))

[ 2 23  4]
[1 3 3]


In [19]:
import tensorflow as tf 
def cond(time, output_ta_l):
    return tf.less(time, 3)
def body(time, output_ta_l):
    output_ta_l = output_ta_l.write(time, [2.4, 3.5])
    return time + 1, output_ta_l 
time = tf.constant(0) 
output_ta = tf.TensorArray(dtype=tf.float32, size=1, dynamic_size=True) 

last_time, last_out = tf.while_loop(cond, body, loop_vars=[time, output_ta]) 

final_out = last_out.stack() 
with tf.Session() as sess:
    print(sess.run(last_time))
    print(sess.run(final_out))

3
[[2.4 3.5]
 [2.4 3.5]
 [2.4 3.5]]


ta.stack(name=None) 将TensorArray中元素叠起来当做一个Tensor输出