In [1]:
import scipy.io as sio

# 导入mat文件

In [2]:
data2 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data2_train.mat')

In [3]:
data3 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data3_train.mat')

In [4]:
data5 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data5_train.mat')

In [5]:
data6 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data6_train.mat')

In [6]:
data8 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data8_train.mat')

In [7]:
data10 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data10_train.mat')

In [8]:
data11 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data11_train.mat')

In [9]:
data12 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data12_train.mat')

In [10]:
data14 = sio.loadmat('F:\jupyter\9个类别的数据集-train\data14_train.mat')

# 数据的提取和拼接

In [11]:
import numpy as np

In [12]:
data2 = data2['data2_train']
data3 = data3['data3_train']
data5 = data5['data5_train']
data6 = data6['data6_train']
data8 = data8['data8_train']
data10 = data10['data10_train']
data11 = data11['data11_train']
data12 = data12['data12_train']
data14 = data14['data14_train']

In [13]:
print(len(data2))
print(len(data3))
print(len(data5))
print(len(data6))
print(len(data8))
print(len(data10))
print(len(data11))
print(len(data12))
print(len(data14))

1071
622
362
547
358
729
1841
445
949


In [14]:
data = np.concatenate((data2,data3),axis=0)

In [15]:
data = np.concatenate((data,data5),axis=0)

In [16]:
data = np.concatenate((data,data6),axis=0)

In [17]:
data = np.concatenate((data,data8),axis=0)

In [18]:
data = np.concatenate((data,data10),axis=0)

In [19]:
data = np.concatenate((data,data11),axis=0)

In [20]:
data = np.concatenate((data,data12),axis=0)

In [21]:
data = np.concatenate((data,data14),axis=0)

In [22]:
data.shape

(6924, 200)

In [34]:
import pandas as pd

In [23]:
data = pd.DataFrame(data)

In [24]:
data.to_csv(".\\data.csv",index=False,header=False)

# labels 的创建

In [23]:
y2 = np.linspace(2,2,data2.shape[0])
y3 =np.linspace(3,3,data3.shape[0])
y5 = np.linspace(5,5,data5.shape[0])
y6 = np.linspace(6,6,data6.shape[0])
y8 = np.linspace(8,8,data8.shape[0])
y10 = np.linspace(10,10,data10.shape[0])
y11 = np.linspace(11,11,data11.shape[0])
y12 = np.linspace(12,12,data12.shape[0])
y14 = np.linspace(14,14,data14.shape[0])

In [24]:
y = np.concatenate((y2,y3),axis=0)

In [25]:
y = np.concatenate((y,y5),axis=0)

In [26]:
y = np.concatenate((y,y6),axis=0)

In [27]:
y = np.concatenate((y,y8),axis=0)

In [28]:
y = np.concatenate((y,y10),axis=0)

In [29]:
y = np.concatenate((y,y11),axis=0)

In [30]:
y = np.concatenate((y,y12),axis=0)

In [31]:
y = np.concatenate((y,y14),axis=0)

In [32]:
y.shape

(6924,)

In [35]:
y = pd.DataFrame(y)

In [36]:
y.to_csv('.\\y.csv',index=False,header=False)

# 数据集的预处理

In [37]:
x = pd.DataFrame(pd.read_csv('./data.csv',header=None))

In [38]:
x = np.array(x)

In [39]:
x.shape

(6924, 200)

In [40]:
y = pd.DataFrame(pd.read_csv('./y.csv',header=None))

In [41]:
y = np.ravel(y)

In [42]:
y.shape

(6924,)

In [43]:
from sklearn.cross_validation import train_test_split

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [45]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
clf = RandomForestClassifier(n_estimators=300,class_weight="balanced",oob_score=True)

In [48]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=300, n_jobs=1, oob_score=True, random_state=None,
            verbose=0, warm_start=False)

In [49]:
a = clf.predict(x_test)

In [50]:
a

array([14., 11., 14., ..., 11., 11.,  2.])

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
C=confusion_matrix(y_test,a)

In [53]:
C

array([[278,   2,   0,   1,   0,   5,  42,   2,   0],
       [  9, 127,   0,   0,   0,   0,  32,   8,   0],
       [  0,   0, 110,   1,   0,   0,   1,   0,   2],
       [  0,   0,   0, 160,   0,   0,   0,   0,   0],
       [  0,   0,   1,   0, 113,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0, 184,  21,   2,   0],
       [ 13,   0,   0,   4,   0,  15, 524,   4,   0],
       [  9,   6,   0,   1,   0,   1,  10, 103,   0],
       [  0,   0,   4,   0,   0,   0,   0,   0, 281]], dtype=int64)

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
accuracy_score(y_test,a)

0.904716073147257

# 预测

In [56]:
test = sio.loadmat('F:\jupyter\data_test_final.mat')

In [57]:
test

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Dec 06 16:57:14 2018',
 '__version__': '1.0',
 'data_test_final': array([[3158, 4122, 4145, ..., 1022, 1019, 1010],
        [3023, 3737, 4027, ..., 1019, 1008, 1004],
        [2743, 4388, 4591, ..., 1056, 1030, 1025],
        ...,
        [2561, 3881, 4051, ..., 1018,  998, 1015],
        [2745, 4391, 4335, ..., 1046, 1029, 1019],
        [3009, 3986, 3967, ..., 1011, 1009, 1000]], dtype=uint16)}

In [58]:
test = test['data_test_final']

In [59]:
test

array([[3158, 4122, 4145, ..., 1022, 1019, 1010],
       [3023, 3737, 4027, ..., 1019, 1008, 1004],
       [2743, 4388, 4591, ..., 1056, 1030, 1025],
       ...,
       [2561, 3881, 4051, ..., 1018,  998, 1015],
       [2745, 4391, 4335, ..., 1046, 1029, 1019],
       [3009, 3986, 3967, ..., 1011, 1009, 1000]], dtype=uint16)

In [60]:
test_y = clf.predict(test)

In [61]:
test_y.shape

(2310,)

In [62]:
test_y

array([12.,  5.,  3., ..., 14., 12.,  6.])

In [63]:
test_y = pd.DataFrame(test_y)

In [64]:
test_y.to_csv('.\\test_y.csv',index=False,header=False)